# Generated by Django 5.0.3 on 2024-03-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('medical_history', models.TextField()),
                ('fitness_record', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='driver_profiles/')),
            ],
        ),
    ]
