# Generated by Django 5.0.3 on 2024-03-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('license_number', models.CharField(max_length=50)),
                ('medical_history', models.TextField(blank=True)),
                ('fitness_records', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
